// authentication & authorization
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCES = 'AUTH_SUCCES';
export const AUTH_FAIL = 'AUTH_FAIL';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCES = 'LOGIN_SUCCES';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const REDIRECT = 'REDIRECT';

export const CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS';
export const CURRENT_USER_START = 'CURRENT_USER_START';
export const CURRENT_USER_FAIL = 'CURRENT_USER_FAIL';

export const GET_USER_CHOICE = 'GET_USER_CHOICE';
// sales invoice
export const SALES_PAGE_OPEN = 'SALES_PAGE_OPEN';
export const SALES_PAGE_CLOSE = 'SALES_PAGE_CLOSE';

export const CREATE_INVOICE_SUCCESS = 'CREATE_INVOICE_SUCCESS';
export const CREATE_INVOICE_FAIL = 'CREATE_INVOICE_FAIL';

export const DELETE_WINDOW_OPEN = 'DELETE_WINDOW_OPEN';
export const DELETE_WINDOW_CLOSE = 'DELETE_WINDOW_CLOSE';
export const DELETE_INVOICE_SUCCESS = "DELETE_INVOICE_SUCCESS";
export const DELETE_INVOICE_FAIL = "DELETE_INVOICE_FAIL";

export const EDIT_WINDOW_OPEN = 'EDIT_WINDOW_OPEN';
export const EDIT_WINDOW_CLOSE = 'EDIT_WINDOW_CLOSE';
export const EDIT_INVOICE_SUCCESS = "EDIT_INVOICE_SUCCESS";
export const EDIT_INVOICE_FAIL = "EDIT_INVOICE_FAIL";

export const DEFAULT_ACCOUNT_START = "DEFAULT_ACCOUNT_START";
export const DEFAULT_ACCOUNT_SUCCESS = "DEFAULT_ACCOUNT_SUCCESS";
export const DEFAULT_ACCOUNT_FAIL = "DEFAULT_ACCOUNT_FAIL";

export const ACCOUNTS_START = "ACCOUNTS_START";
export const ACCOUNTS_SUCCESS = "ACCOUNTS_SUCCESS";
export const ACCOUNTS_FAIL = "ACCOUNTS_FAIL";
// COSTOMER_RECIEPT
export const CUSTOMER_RECIEPT_PAGE_OPEN = "CUSTOMER_RECIEPT_PAGE_OPEN";
export const CUSTOMER_RECIEPT_PAGE_CLOSE = "CUSTOMER_RECIEPT_PAGE_CLOSE";

export const CREATE_CUSTOMER_RECIEPT_SUCCESS = 'CREATE_CUSTOMER_RECIEPT_SUCCESS';
export const CREATE_CUSTOMER_RECIEPT_FAIL = 'CREATE_CUSTOMER_RECIEPT_FAIL';

export const CUSTOMER_RECIEPT_DELETE_WINDOW_OPEN = 'CUSTOMER_RECIEPT_DELETE_WINDOW_OPEN';
export const CUSTOMER_RECIEPT_DELETE_WINDOW_CLOSE = 'CUSTOMER_RECIEPT_DELETE_WINDOW_CLOSE';
export const CUSTOMER_RECIEPT_DELETE_SUCCESS = "CUSTOMER_RECIEPT_DELETE_SUCCESS";
export const CUSTOMER_RECIEPT_DELETE_FAIL = "CUSTOMER_RECIEPT_DELETE_FAIL";

export const CUSTOMER_RECIEPT_EDIT_WINDOW_OPEN = 'CUSTOMER_RECIEPT_EDIT_WINDOW_OPEN';
export const CUSTOMER_RECIEPT_EDIT_WINDOW_CLOSE = 'CUSTOMER_RECIEPT_EDIT_WINDOW_CLOSE';
export const EDIT_CUSTOMER_RECIEPT_SUCCESS = "EDIT_CUSTOMER_RECIEPT_SUCCESS";
export const EDIT_CUSTOMER_RECIEPT_FAIL = "EDIT_CUSTOMER_RECIEPT_FAIL";
// EXPENSE PAGE
export const EXPENSES_LIST_PAGE_OPEN = "EXPENSES_LIST_PAGE_OPEN";
export const EXPENSES_LIST_PAGE_CLOSE = "EXPENSES_LIST_PAGE_CLOSE";

export const CREATE_EXPENSE_SUCCESS = "CREATE_EXPENSE_SUCCESS";
export const CREATE_EXPENSE_FAIL = "CREATE_EXPENSE_FAIL";

export const EXPENSE_DELETE_WINDOW_OPEN = "EXPENSE_DELETE_WINDOW_OPEN";
export const EXPENSE_DELETE_WINDOW_CLOSE = "EXPENSE_DELETE_WINDOW_CLOSE";
export const EXPENSE_DELETE_SUCCESS = "EXPENSE_DELETE_SUCCESS";
export const EXPENSE_DELETE_FAIL = "EXPENSE_DELETE_FAIL";

export const EXPENSE_EDIT_WINDOW_OPEN = "EXPENSE_EDIT_WINDOW_OPEN";
export const EXPENSE_EDIT_WINDOW_CLOSE = "EXPENSE_EDIT_WINDOW_CLOSE";
export const EXPENSE_EDIT_SUCCESS = "EXPENSE_EDIT_SUCCESS";
export const EXPENSE_EDIT_FAIL = "EXPENSE_EDIT_FAIL";
// Partner page
export const PARTNERS_LIST_PAGE_OPEN = "PARTNERS_LIST_PAGE_OPEN";
export const PARTNERS_LIST_PAGE_CLOSE = "PARTNERS_LIST_PAGE_CLOSE";

export const CREATE_PARTNER_SUCCESS = "CREATE_PARTNER_SUCCESS";
export const CREATE_PARTNER_FAIL = "CREATE_PARTNER_FAIL";

export const PARTNER_DELETE_WINDOW_OPEN = "PARTNER_DELETE_WINDOW_OPEN";
export const PARTNER_DELETE_WINDOW_CLOSE = "PARTNER_DELETE_WINDOW_CLOSE";
export const PARTNER_DELETE_SUCCESS = "PARTNER_DELETE_SUCCESS";
export const PARTNER_DELETE_FAIL = "PARTNER_DELETE_FAIL";

export const PARTNER_EDIT_WINDOW_OPEN = "PARTNER_EDIT_WINDOW_OPEN";
export const PARTNER_EDIT_WINDOW_CLOSE = "PARTNER_EDIT_WINDOW_CLOSE";
export const PARTNER_EDIT_SUCCESS = "PARTNER_EDIT_SUCCESS";
export const PARTNER_EDIT_FAIL = "PARTNER_EDIT_FAIL";
// Product page
export const PRODUCT_LIST_PAGE_OPEN = "PRODUCT_LIST_PAGE_OPEN";
export const PRODUCT_LIST_PAGE_CLOSE = "PRODUCT_LIST_PAGE_CLOSE";

export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";

export const PRODUCT_DELETE_WINDOW_OPEN = "PRODUCT_DELETE_WINDOW_OPEN";
export const PRODUCT_DELETE_WINDOW_CLOSE = "PRODUCT_DELETE_WINDOW_CLOSE";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";

export const PRODUCT_EDIT_WINDOW_OPEN = "PRODUCT_EDIT_WINDOW_OPEN";
export const PRODUCT_EDIT_WINDOW_CLOSE = "PRODUCT_EDIT_WINDOW_CLOSE";
export const PRODUCT_EDIT_SUCCESS = "PRODUCT_EDIT_SUCCESS";
export const PRODUCT_EDIT_FAIL = "PRODUCT_EDIT_FAIL";

export const GET_ALL_PRODUCT_CAT_SUCCESS = "GET_ALL_PRODUCT_CAT_SUCCESS";

// ProductCategory
export const PRODUCT_CATEGORY_LIST_PAGE_OPEN = "PRODUCT_CATEGORY_LIST_PAGE_OPEN";
export const PRODUCT_CATEGORY_LIST_PAGE_CLOSE = "PRODUCT_CATEGORY_LIST_PAGE_CLOSE";

export const CREATE_PRODUCT_CATEGORY_SUCCESS = "CREATE_PRODUCT_CATEGORY_SUCCESS";
export const CREATE_PRODUCT_CATEGORY_FAIL = "CREATE_PRODUCT_CATEGORY_FAIL";

export const PRODUCT_CATEGORY_DELETE_WINDOW_OPEN = "PRODUCT_CATEGORY_DELETE_WINDOW_OPEN";
export const PRODUCT_CATEGORY_DELETE_WINDOW_CLOSE = "PRODUCT_CATEGORY_DELETE_WINDOW_CLOSE";
export const PRODUCT_CATEGORY_DELETE_SUCCESS = "PRODUCT_CATEGORY_DELETE_SUCCESS";
export const PRODUCT_CATEGORY_DELETE_FAIL = "PRODUCT_CATEGORY_DELETE_FAIL";

export const PRODUCT_CATEGORY_EDIT_WINDOW_OPEN = "PRODUCT_CATEGORY_EDIT_WINDOW_OPEN";
export const PRODUCT_CATEGORY_EDIT_WINDOW_CLOSE = "PRODUCT_CATEGORY_EDIT_WINDOW_CLOSE";
export const PRODUCT_CATEGORY_EDIT_SUCCESS = "PRODUCT_CATEGORY_EDIT_SUCCESS";
export const PRODUCT_CATEGORY_EDIT_FAIL = "PRODUCT_CATEGORY_EDIT_FAIL";
export const GET_ALL_PRODUCT_CATEGORY_DATA = "GET_ALL_PRODUCT_CATEGORY_DATA";
// branch
export const BRANCH_LIST_PAGE_OPEN = "BRANCH_LIST_PAGE_OPEN";
export const BRANCH_LIST_PAGE_CLOSE = "BRANCH_LIST_PAGE_CLOSE";

export const CREATE_BRANCH_SUCCESS = "CREATE_BRANCH_SUCCESS";
export const CREATE_BRANCH_FAIL = "CREATE_BRANCH_FAIL";

export const BRANCH_DELETE_WINDOW_OPEN = "BRANCH_DELETE_WINDOW_OPEN";
export const BRANCH_DELETE_WINDOW_CLOSE = "BRANCH_DELETE_WINDOW_CLOSE";
export const BRANCH_DELETE_SUCCESS = "BRANCH_DELETE_SUCCESS";
export const BRANCH_DELETE_FAIL = "BRANCH_DELETE_FAIL";

export const BRANCH_EDIT_WINDOW_OPEN = "BRANCH_EDIT_WINDOW_OPEN";
export const BRANCH_EDIT_WINDOW_CLOSE = "BRANCH_EDIT_WINDOW_CLOSE";
export const BRANCH_EDIT_SUCCESS = "BRANCH_EDIT_SUCCESS";
export const BRANCH_EDIT_FAIL = "BRANCH_EDIT_FAIL";
export const GET_ALL_BRANCH_DATA = "GET_ALL_BRANCH_DATA";
// Area
export const AREA_LIST_PAGE_OPEN = "AREA_LIST_PAGE_OPEN";
export const AREA_LIST_PAGE_CLOSE = "AREA_LIST_PAGE_CLOSE";

export const CREATE_AREA_SUCCESS = "CREATE_AREA_SUCCESS";
export const CREATE_AREA_FAIL = "CREATE_AREA_FAIL";

export const AREA_DELETE_WINDOW_OPEN = "AREA_DELETE_WINDOW_OPEN";
export const AREA_DELETE_WINDOW_CLOSE = "AREA_DELETE_WINDOW_CLOSE";
export const AREA_DELETE_SUCCESS = "AREA_DELETE_SUCCESS";
export const AREA_DELETE_FAIL = "AREA_DELETE_FAIL";

export const AREA_EDIT_WINDOW_OPEN = "AREA_EDIT_WINDOW_OPEN";
export const AREA_EDIT_WINDOW_CLOSE = "AREA_EDIT_WINDOW_CLOSE";
export const AREA_EDIT_SUCCESS = "AREA_EDIT_SUCCESS";
export const AREA_EDIT_FAIL = "AREA_EDIT_FAIL";
export const GET_ALL_AREA_DATA = "GET_ALL_AREA_DATA";
