// authentication & authorization
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCES = 'AUTH_SUCCES';
export const AUTH_FAIL = 'AUTH_FAIL';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCES = 'LOGIN_SUCCES';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const REDIRECT = 'REDIRECT';

export const CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS';
export const CURRENT_USER_START = 'CURRENT_USER_START';
export const CURRENT_USER_FAIL = 'CURRENT_USER_FAIL';

export const GET_USER_CHOICE = 'GET_USER_CHOICE';
// sales invoice
export const SALES_PAGE_OPEN = 'SALES_PAGE_OPEN';
export const SALES_PAGE_CLOSE = 'SALES_PAGE_CLOSE';

export const CREATE_INVOICE_SUCCESS = 'CREATE_INVOICE_SUCCESS';
export const CREATE_INVOICE_FAIL = 'CREATE_INVOICE_FAIL';

export const DELETE_WINDOW_OPEN = 'DELETE_WINDOW_OPEN';
export const DELETE_WINDOW_CLOSE = 'DELETE_WINDOW_CLOSE';
export const DELETE_INVOICE_SUCCESS = "DELETE_INVOICE_SUCCESS";
export const DELETE_INVOICE_FAIL = "DELETE_INVOICE_FAIL";

export const EDIT_WINDOW_OPEN = 'EDIT_WINDOW_OPEN';
export const EDIT_WINDOW_CLOSE = 'EDIT_WINDOW_CLOSE';
export const EDIT_INVOICE_SUCCESS = "EDIT_INVOICE_SUCCESS";
export const EDIT_INVOICE_FAIL = "EDIT_INVOICE_FAIL";

export const DEFAULT_ACCOUNT_START = "DEFAULT_ACCOUNT_START";
export const DEFAULT_ACCOUNT_SUCCESS = "DEFAULT_ACCOUNT_SUCCESS";
export const DEFAULT_ACCOUNT_FAIL = "DEFAULT_ACCOUNT_FAIL";

export const ACCOUNTS_START = "ACCOUNTS_START";
export const ACCOUNTS_SUCCESS = "ACCOUNTS_SUCCESS";
export const ACCOUNTS_FAIL = "ACCOUNTS_FAIL";
// COSTOMER_RECIEPT
export const CUSTOMER_RECIEPT_PAGE_OPEN = "CUSTOMER_RECIEPT_PAGE_OPEN";
export const CUSTOMER_RECIEPT_PAGE_CLOSE = "CUSTOMER_RECIEPT_PAGE_CLOSE";

export const CREATE_CUSTOMER_RECIEPT_SUCCESS = 'CREATE_CUSTOMER_RECIEPT_SUCCESS';
export const CREATE_CUSTOMER_RECIEPT_FAIL = 'CREATE_CUSTOMER_RECIEPT_FAIL';

export const CUSTOMER_RECIEPT_DELETE_WINDOW_OPEN = 'CUSTOMER_RECIEPT_DELETE_WINDOW_OPEN';
export const CUSTOMER_RECIEPT_DELETE_WINDOW_CLOSE = 'CUSTOMER_RECIEPT_DELETE_WINDOW_CLOSE';
export const CUSTOMER_RECIEPT_DELETE_SUCCESS = "CUSTOMER_RECIEPT_DELETE_SUCCESS";
export const CUSTOMER_RECIEPT_DELETE_FAIL = "CUSTOMER_RECIEPT_DELETE_FAIL";

export const CUSTOMER_RECIEPT_EDIT_WINDOW_OPEN = 'CUSTOMER_RECIEPT_EDIT_WINDOW_OPEN';
export const CUSTOMER_RECIEPT_EDIT_WINDOW_CLOSE = 'CUSTOMER_RECIEPT_EDIT_WINDOW_CLOSE';
export const EDIT_CUSTOMER_RECIEPT_SUCCESS = "EDIT_CUSTOMER_RECIEPT_SUCCESS";
export const EDIT_CUSTOMER_RECIEPT_FAIL = "EDIT_CUSTOMER_RECIEPT_FAIL";
// EXPENSE PAGE
export const EXPENSES_LIST_PAGE_OPEN = "EXPENSES_LIST_PAGE_OPEN";
export const EXPENSES_LIST_PAGE_CLOSE = "EXPENSES_LIST_PAGE_CLOSE";

export const CREATE_EXPENSE_SUCCESS = "CREATE_EXPENSE_SUCCESS";
export const CREATE_EXPENSE_FAIL = "CREATE_EXPENSE_FAIL";

export const EXPENSE_DELETE_WINDOW_OPEN = "EXPENSE_DELETE_WINDOW_OPEN";
export const EXPENSE_DELETE_WINDOW_CLOSE = "EXPENSE_DELETE_WINDOW_CLOSE";
export const EXPENSE_DELETE_SUCCESS = "EXPENSE_DELETE_SUCCESS";
export const EXPENSE_DELETE_FAIL = "EXPENSE_DELETE_FAIL";

export const EXPENSE_EDIT_WINDOW_OPEN = "EXPENSE_EDIT_WINDOW_OPEN";
export const EXPENSE_EDIT_WINDOW_CLOSE = "EXPENSE_EDIT_WINDOW_CLOSE";
export const EXPENSE_EDIT_SUCCESS = "EXPENSE_EDIT_SUCCESS";
export const EXPENSE_EDIT_FAIL = "EXPENSE_EDIT_FAIL";
