export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCES = 'AUTH_SUCCES';
export const AUTH_FAIL = 'AUTH_FAIL';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCES = 'LOGIN_SUCCES';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const REDIRECT = 'REDIRECT';

export const CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS';
export const CURRENT_USER_START = 'CURRENT_USER_START';
export const CURRENT_USER_FAIL = 'CURRENT_USER_FAIL';

export const GET_USER_CHOICE = 'GET_USER_CHOICE';

export const SALES_PAGE_OPEN = 'SALES_PAGE_OPEN';
export const SALES_PAGE_CLOSE = 'SALES_PAGE_CLOSE';

export const CREATE_INVOICE_SUCCESS = 'CREATE_INVOICE_SUCCESS';
export const CREATE_INVOICE_FAIL = 'CREATE_INVOICE_FAIL';

export const DELETE_WINDOW_OPEN = 'DELETE_WINDOW_OPEN';
export const DELETE_WINDOW_CLOSE = 'DELETE_WINDOW_CLOSE';
export const DELETE_INVOICE_SUCCESS = "DELETE_INVOICE_SUCCESS";
export const DELETE_INVOICE_FAIL = "DELETE_INVOICE_FAIL";

export const EDIT_WINDOW_OPEN = 'EDIT_WINDOW_OPEN';
export const EDIT_WINDOW_CLOSE = 'EDIT_WINDOW_CLOSE';
export const EDIT_INVOICE_SUCCESS = "EDIT_INVOICE_SUCCESS";
export const EDIT_INVOICE_FAIL = "EDIT_INVOICE_FAIL";
